n, m = map(int, input().split())
se1, se2 = set(), set()
a = list(map(int, input().split()))
b = list(map(int, input().split()))
for item in a: se1.add(item)
for item in b: se2.add(item)
sorted(se1)
sorted(se2)
if se1 == se2: print("YES")
else: print("NO")